# Generated by Django 4.2.3 on 2023-07-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_categoria_options_eventos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventos',
            new_name='Evento',
        ),
    ]
