# Generated by Django 4.2.3 on 2023-07-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=50, verbose_name='Nome do Pet')),
                ('telefone', models.CharField(max_length=11)),
                ('dia_reserva', models.DateField(verbose_name='Dia da reserva')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
        ),
    ]
