# Generated by Django 4.2.3 on 2023-07-18 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='preferencia_evento',
            field=models.CharField(choices=[('todos', 'Todos'), ('musicais', 'Eventos Musicais'), ('esportivos', 'Eventos Esportivos'), ('educativos', 'Eventos Educativos')], default='todos', max_length=20, verbose_name='Preferência de Evento'),
        ),
    ]
